Use fly instead of curl for pre-push hook
Co-authored-by: Kieron Browne <kbrowne@pivotal.io>

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -36,11 +36,19 @@ prompt-push() {
   esac
 }
 
+fly-login() {
+  if ! flightattendant -target eirini; then
+    fly -t eirini login --team-name main --concourse-url https://jetson.eirini.cf-app.com/ </dev/tty
+  fi
+}
+
 check-pipeline() {
   local pipeline_name failed_jobs
   pipeline_name="$1"
   echo "Checking https://jetson.eirini.cf-app.com/teams/main/pipelines/$pipeline_name ..."
-  curl -s "https://jetson.eirini.cf-app.com/api/v1/teams/main/pipelines/$pipeline_name/jobs" | grep -Eq "failed|error"
+  fly-login
+  output=$(fly -t eirini jobs -p "$1")
+  echo "$output" | grep -Eq "failed|error"
 }
 
 main
